### ISSUE TITLE
phantasmal world4 map name error

### ISSUE THREAD

**Issue by wangzhenxyz1** [DaanVandenBosch/phantasmal-world#11]
west tower maps locate on Seaside Area At Night.

**Comment by DaanVandenBosch** [comment]
You're right, we load the right map but the name is still "Seaside Area At Night" while it should be "West Tower". I'll fix it at some point, thanks for pointing it out.

**Comment by DaanVandenBosch** [comment]
This issue is fixed by 445878fb6e937b2ed4038ca415737ee280ba61fc.

**Comment by warmonipa** [comment]
> This issue is fixed by [445878f](https://github.com/DaanVandenBosch/phantasmal-world/commit/445878fb6e937b2ed4038ca415737ee280ba61fc).

#33
