### ISSUE TITLE
Request features

### ISSUE THREAD

**Issue by wangzhenxyz1** [DaanVandenBosch/phantasmal-world#13]
Request RoomId , Coordinates , Wrap target, position y switch(land in air y>0),  thank you!

**Comment by DaanVandenBosch** [comment]
If you're talking about room ID and coordinates of NPCs/enemies/objects, that's already there (called section ID and position). I'm not sure what you mean by wrap target and position y switch.

**Comment by wangzhenxyz1** [comment]
Thank you for reply!
I mean wrap target is the destination sign on the map of wrap object,
position Y is the vertical coordinate of monster, if Y > 0 then monster will fly in the air, 
for example , sinow beat's position Y is 214 in endless nightmare 3 - EP1.

**Comment by DaanVandenBosch** [comment]
I think I understand what you mean, I'll probably implement it sometime.

**Comment by wangzhenxyz1** [comment]
> I think I understand what you mean, I'll probably implement it sometime.

sound good, 👍

**Comment by DaanVandenBosch** [comment]
You can now see the destination of all warps in the 3D view and when you select a warp, a line is drawn from the warp to its destination:

![image](https://user-images.githubusercontent.com/18369066/120687219-14f0bf00-c4a2-11eb-9239-237af323d509.png)

Later on I want to make it possible to move/rotate the warp destination directly via the 3D view just like you can with enemies and objects.

I've also added the "Invisible" field that qedit has for sinows, but I'm not sure that's what you're asking for.

**Comment by wangzhenxyz1** [comment]
Cool! Great work, nice designator.

We hope to see sinow-type monster on the floor instead of floating in the air.

**Comment by warmonipa** [comment]
#30 RoomId , Coordinates , position y switch(land in air y>0),
