### ISSUE TITLE
[Question] import seabed maps

### ISSUE THREAD

**Issue by Deflaktor** [DaanVandenBosch/phantasmal-world#14]
First of all, wow this is some crazy project!

I wanted to view the seabed and other maps from episode 2, but when I load the files the texture are all messed up. Is there something im doing wrong?

**Comment by DaanVandenBosch** [comment]
Are you talking about the black quads around most of the rooms?

![image](https://user-images.githubusercontent.com/18369066/142720622-e599ab30-a84a-4ffa-8abc-b2f03ca22a99.png)

If that's the case, that's indeed a bug that needs to be fixed sometime. But I'm not sure these quads are supposed to be textured.

**Comment by Deflaktor** [comment]
Ah I was opening the models wrongly. It works fine, thanks!
