### ISSUE TITLE
Coordinates in 3D view differ from X, Y, Z values in scripts

### ISSUE THREAD

**Issue by Shade53** [DaanVandenBosch/phantasmal-world#17]
Hi, I've started using your quest editor in place of QEdit, since it is far more user friendly, however I've noticed that the coordinates listed on entities seems to differ greatly from the ones used in scripts.
I have placed an NPC where I expect the normal quest starting position to be:
![image](https://github.com/user-attachments/assets/804b151c-ce30-425e-bef3-e2184ed32a45)

But I see the coordinates in the entity panel are MUCH farther away from the default positions used in the script:
![image](https://github.com/user-attachments/assets/3b3a7ebc-363b-4110-9bed-18334a489671)

I've even tried taking the coordinates from the script and placing them in the appropriate X, Y, Z and rotation fields(Y in rotation, allowing it to underflow the value) and I find the NPC to be out in space instead of on the Pioneer. The only thing that seems correct is the rotation value when it underflows produces a rotation value of 345, which works out great, but the NPC is still not in the place that I want the player to be:
![image](https://github.com/user-attachments/assets/95e858f8-0c1c-4341-8423-18b29e9ba4f1)

My concern is: How am I supposed to get accurate coordinates for the script in the 3D view?

I am running the newest clone of the webserver from your main branch, so I have all the newest features, is this working as intended and if so, is there maybe some math I should be using to convert coordinate values from the NPC's/Objects in the 3D View to the script, or will the script accept old QEdit coords AND new Phantasmal coords?

I can see that you have moved on to other projects for the most part, but any help would be appreciated.

**Comment by DaanVandenBosch** [comment]
Phantasmal world shows the same values as qedit, so at least we're consistent. It looks like the script coordinates are absolute world coordinates, while the object/NPC coordinates are section-relative. The quest editor doesn't have a way of displaying the world coordinates at the moment. I guess we have a good reason now to show world coords somewhere.

**Comment by DaanVandenBosch** [comment]
I've added world coords to the entity view, they still seem to be off from the coords in the script. A bit weird, but maybe the devs just tweaked one and forgot to update the other and it doesn't really matter to the game?

**Comment by Shade53** [comment]
Oh yeah! It has been soo long since I last worked on a PSO quest I forgot that entities set their '0' to the center of the room/section they are assigned to. And just like that I was able to get the world coords by just setting the entity's section ID to 0. Was able to verify this by now taking the default p_setpos coords and putting them into the entity coords and the entity now ends up where I expect the player to end up!

It would still be nice if we could get a display of the coordinates based on "current floor center" for use with OPCodes that don't take room/section ID values, but for now I can work around this by just setting an entity to section 0, then placing it where I want to get the coordinates from so I can use the coords from the entity in the code. I just need to make sure I remember to delete the entity when I am done using it for coords.

I can close this as resolved, unless you would rather have me keep this open as a "Feature Request" of sorts for an easier way to get the "world coords" of OPCodes that use them?

**Comment by DaanVandenBosch** [comment]
This is exactly the feature I implemented, unless we're talking about two different things:
![image](https://github.com/user-attachments/assets/23ff9185-6f20-4013-8103-c9205f3f061d)

Do you mean something else by 'display of the coordinates based on "current floor center"'?
